/**
 * @module pdf-report
 * @desc Generates a static, print-optimised HTML string for PDF export.
 *
 * @logic
 * Completely separate from the interactive HTML dashboard (html.js).
 * No search bars, no filter buttons, no tabs, no JavaScript.
 * Vulnerabilities are grouped by severity in a fixed-layout table
 * with word-break on every cell — nothing overflows or gets clipped.
 * All styles are inlined so Puppeteer renders correctly with
 * printBackground: true.
 *
 * @note
 * Column widths are tuned for A4 (210mm) with 16mm side margins.
 * Severity 10% · Package 18% · Advisory 17% · Summary 33% · Projects 22%
 */

import { DARK_THEME as C } from "../themes/dark.js";
import { STYLESHEET, PILL } from "./pdf-styles.js";
import { renderSummaryCards, renderSeveritySections } from "./pdf-layout.js";

export function renderPDFReport(report) {
  const { scannedAt, meta, counts, groups } = report;
  const hasVulns = meta.totalVulnerabilities > 0;

  const date = new Date(scannedAt).toLocaleString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const summaryCards = renderSummaryCards(counts);
  const sections = renderSeveritySections(groups);

  return /* html */ `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>${STYLESHEET}</style>
</head>
<body>

  <div style="border-bottom:1px solid ${C.bgBorder}; padding-bottom:20px; margin-bottom:25px;">
    <div style="font-size:9px;letter-spacing:2px;text-transform:uppercase;color:${C.accent};font-family:monospace;margin-bottom:8px;">👁 DEP-SCANNER</div>
    <div style="font-size:26px;font-weight:700;letter-spacing:-.5px;color:#ffffff;margin-bottom:4px;">
      Dependency Vulnerability Report
    </div>
    <div style="font-size:12px;color:${C.textMuted};margin-bottom:15px;">${date}</div>
    <div style="display:flex;gap:10px;">
      <span style="${PILL}">📁 ${meta.totalProjects} projects</span>
      <span style="${PILL}">📦 ${meta.totalScanned} scanned</span>
      ${
        hasVulns
          ? `<span style="${PILL}background:rgba(218,54,51,.2);border-color:#da3633;color:#ff7b72;">⚠️ ${meta.totalVulnerabilities} vulnerabilities</span>`
          : `<span style="${PILL}background:rgba(46,160,67,.2);border-color:#2ea043;color:#56d364;">✓ Clean</span>`
      }
    </div>
  </div>

  <div style="display:flex;gap:12px;margin-bottom:32px;">
    ${summaryCards}
  </div>

  ${hasVulns ? sections : `<div style="text-align:center;padding:60px;color:${C.textMuted};">...No Issues...</div>`}

  <div style="border-top:1px solid ${C.bgBorder}; margin-top:40px; padding-top:15px; font-size:10px; color:${C.textDim}; display:flex; justify-content:space-between;">
    <span>Generated by <strong>dep-scanner</strong> · Data from osv.dev</span>
    <span>${new Date().getFullYear()} Report</span>
  </div>

</body>
</html>`;
}
